// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cntabfwqrucajogqnjjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudGFiZndxcnVjYWpvZ3FuampzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjk0MjcsImV4cCI6MjA2MjcwNTQyN30.JXXovlZAAW1d4P-d36x2ZpPr19Ny9ofwHedqm0iq3co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);